//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorunLive.Application.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TorunLive.Application.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!doctype html&gt;
        ///&lt;!--[if lt IE 8 ]&gt;&lt;html class=&quot;no-js ie ie7&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 8 ]&gt;&lt;html class=&quot;no-js ie&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if (gt IE 8)|!(IE)]&gt;&lt;!--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head id=&quot;ctl00_ctl00_headMaster&quot;&gt;&lt;meta charset=&quot;UTF-8&quot; /&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot; /&gt;&lt;title&gt;
        ///	TORUŃ Serwis transport publiczny
        ///&lt;/title&gt;&lt;meta name=&quot;description&quot; content=&quot;GMV Public transport service&quot; /&gt;&lt;meta name=&quot;keywords&quot; content=&quot;GMV Public transport service&quot; /&gt;&lt;meta n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string liveNewResponse {
            get {
                return ResourceManager.GetString("liveNewResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|#||4|53|updatePanel|ctl00_ctl00_ContentPlaceHolderContenido_UpdatePanelTime|
        ///                        00:11
        ///                    |2236|updatePanel|ctl00_ctl00_ContentPlaceHolderContenido_UpdatePanel1|
        ///                        
        ///    
        ///            &lt;table class=&quot;&quot;tablePanel&quot;&quot; style=&quot;&quot;width: 100%;&quot;&quot;&gt;
        ///                &lt;thead&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;th scope=&quot;&quot;col&quot;&quot; style=&quot;&quot;width: 50px;&quot;&quot;&gt;
        ///                            Linia
        ///                        &lt;/th&gt;
        ///                        
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string liveUpdateResponse {
            get {
                return ResourceManager.GetString("liveUpdateResponse", resourceCulture);
            }
        }
    }
}
